/**
 *   Copyright (c) Telicent Ltd.
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
package io.telicent.smart.cache.entity.sinks.converters;

/**
 * Useful constants for default output fields
 */
public final class DefaultOutputFields {

    /**
     * Private constructor prevents instantiation
     */
    private DefaultOutputFields() {
    }

    /**
     * Default output field for the URI
     */
    public static final String URI = "uri";

    /**
     * Default output field for the primary name
     */
    public static final String PRIMARY_NAME = "primaryName";

    /**
     * Default output field for the primary image
     */
    public static final String PRIMARY_IMAGE = "primaryImage";

    /**
     * Default output field for Types
     */
    public static final String TYPES = "types";

    /**
     * Default output field for Literals
     */
    public static final String LITERALS = "literals";

    /**
     * Default output field for security labels information
     */
    public static final String SECURITY_LABELS = "securityLabels";

    /**
     * Default output subfield for security labels graph
     */
    public static final String SECURITY_LABELS_SUB_FIELD_GRAPH = "graph";
    /**
     * Default output subfield for default security labels
     */
    public static final String SECURITY_LABELS_SUB_FIELD_DEFAULTS = "defaults";

    /**
     * Default output field for metadata
     */
    public static final String METADATA = "metadata";

    /**
     * Default output field for metadata content type
     */
    public static final String METADATA_CONTENT_TYPE = "metadata.Content-Type";

    /**
     * Default output field for metadata content length
     */
    public static final String METADATA_CONTENT_LENGTH = "metadata.Content-Length";

    /**
     * Default output field for generated at metadata
     */
    public static final String GENERATED_AT = "generatedAt";

    /**
     * Default output field for generated by metadata
     */
    public static final String GENERATED_BY = "generatedBy";

    /**
     * Default output field for generator version metadata
     */
    public static final String GENERATOR_VERSION = "generatorVersion";

    /**
     * Default output field for generator document format metadata
     */
    public static final String DOCUMENT_FORMAT = "documentFormat";

    /**
     * Default output field for document title
     */
    public static final String TITLE = "Title";

    /**
     * Default output field for document textual content
     */
    public static final String CONTENT = "content";
}
